// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace Stats.Api.Entities
{
    public partial class ByEmployeeTotalTimeInMeetingsResult
    {
        public int? EmployeeTotalTime { get; set; }
        public string DisplayName { get; set; }
        public string Email { get; set; }
    }
}
