// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Stats.Api.Entities;

public partial class DataPullLogs
{
    public int Id { get; set; }

    public string PullType { get; set; }

    public DateTime PullDate { get; set; }

    public string Parameters { get; set; }
}