// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace Stats.Api.Entities
{
    public partial class EmployeeNamesResult
    {
        public string displayname { get; set; }
    }
}
