// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Stats.Api.Entities;

public partial class FiServeTotalEmpMeetingsView
{
    public string DisplayName { get; set; }

    public int? Totaltime { get; set; }
}