// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.Data.SqlClient;
using Microsoft.EntityFrameworkCore;
using Stats.Api.Entities;
using System;
using System.Collections.Generic;
using System.Data;
using System.Threading;
using System.Threading.Tasks;

namespace Stats.Api.Entities
{
    public partial interface IWebExStatsContextProcedures
    {
        Task<int> AddMeetingAsync(string Id, string MeetingSeriesId, string ScheduledMeetingId, string Title, string MeetingType, string State, string Timezone, DateTime? Start, DateTime? End, string HostUserId, string HostDisplayName, string HostEmail, string SiteUrl, string ScheduledType, bool? HasChat, bool? HasRecording, bool? HasTranscription, bool? HasClosedCaption, bool? HasPolls, bool? HasQA, string MeetingNumber, bool? EnabledAutoRecordMeeting, bool? AllowAnyUserToBeCoHost, bool? AllowFirstUserToBeCoHost, bool? AllowAuthenticatedDevices, bool? EnabledJoinBeforeHost, int? JoinBeforeHostMinutes, bool? EnableConnectAudioBeforeHost, bool? ExcludePassword, bool? PublicMeeting, bool? EnableAutomaticLock, int? SessionTypeId, int? ReminderTime, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<int> AddParticipantAsync(string Id, bool? Host, bool? CoHost, bool? SpaceModerator, string Email, string DisplayName, bool? Invitee, bool? Muted, string State, DateTime? JoinedTime, DateTime? LeftTime, string SiteUrl, string MeetingId, string HostEmail, DateTime? MeetingTimeStart, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<int> AddPullLogAsync(string PullType, DateTime? PullDate, string Parameters, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<AllEmployeesInAllMeetingsResult>> AllEmployeesInAllMeetingsAsync(DateTime? StartDate, DateTime? EndDate, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<ByEmployeeTotalTimeInMeetingsResult>> ByEmployeeTotalTimeInMeetingsAsync(DateTime? StartDate, DateTime? EndDate, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<EmployeeMeetingsResult>> EmployeeMeetingsAsync(string Email, string DisplayName, DateTime? StartDate, DateTime? EndDate, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<EmployeeMeetingTotalTimeResult>> EmployeeMeetingTotalTimeAsync(DateTime? StartDate, DateTime? EndDate, string Email, string DisplayName, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<EmployeeNamesResult>> EmployeeNamesAsync(OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<EmployeeTotalFiServMeetingsResult>> EmployeeTotalFiServMeetingsAsync(string Email, string DisplayName, DateTime? StartDate, DateTime? EndDate, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<EmployeeTotalNonFiServMeetingsResult>> EmployeeTotalNonFiServMeetingsAsync(string Email, string DisplayName, DateTime? StartDate, DateTime? EndDate, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<GetMeetingsNoParticipantsResult>> GetMeetingsNoParticipantsAsync(OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<LastDataPullResult>> LastDataPullAsync(string PullType, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<MeetingParticipantsListResult>> MeetingParticipantsListAsync(string MeetingId, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<int> SetParticipantsPulledAsync(string Id, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<StartEndDatesResult>> StartEndDatesAsync(OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<TopFiservUsersResult>> TopFiservUsersAsync(string Filter, DateTime? StartDate, DateTime? EndDate, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<TopUsersResult>> TopUsersAsync(DateTime? StartDate, DateTime? EndDate, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<TotalEmployeeTimeInAllMeetingsResult>> TotalEmployeeTimeInAllMeetingsAsync(DateTime? StartDate, DateTime? EndDate, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<TotalTimePerMonthResult>> TotalTimePerMonthAsync(DateTime? StartDate, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
    }
}
