// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Stats.Api.Entities;

public partial class MeetingParticipantDateView
{
    public DateTime? MeetingStart { get; set; }

    public DateTime? MeetingEnd { get; set; }

    public string Title { get; set; }

    public string DisplayName { get; set; }

    public int? EmployeeTime { get; set; }

    public string MeetingId { get; set; }

    public string Email { get; set; }
}