// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Stats.Api.Entities;

public partial class MeetingParticipantTimeView
{
    public string DisplayName { get; set; }

    public string Email { get; set; }

    public string Title { get; set; }

    public bool? Host { get; set; }

    public int? Meetinglength { get; set; }

    public int? Participantlength { get; set; }
}