// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace Stats.Api.Entities
{
    public partial class MeetingParticipantsListResult
    {
        public long DbId { get; set; }
        public string Id { get; set; }
        public string DisplayName { get; set; }
        public int? ParticipantTime { get; set; }
    }
}
