// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace Stats.Api.Entities
{
    public partial class StartEndDatesResult
    {
        public DateTime? startDate { get; set; }
        public DateTime? endDate { get; set; }
    }
}
