// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Stats.Api.Entities;

public partial class Tokens
{
    public int Id { get; set; }

    public string TokenName { get; set; }

    public string Token { get; set; }
}