// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace Stats.Api.Entities
{
    public partial class TopFiservUsersResult
    {
        public string displayname { get; set; }
        public string email { get; set; }
        public int? emptime { get; set; }
    }
}
