// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Stats.Api.Entities;

public partial class TotalTimePerMonthView
{
    public string Id { get; set; }

    public string Title { get; set; }

    public DateTime? Startmonth { get; set; }

    public DateTime? Endmonth { get; set; }

    public int? Participantlength { get; set; }
}