// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;

namespace Stats.Api.Entities;

public partial class WebExStatsContext : DbContext
{
    public WebExStatsContext(DbContextOptions<WebExStatsContext> options)
        : base(options)
    {
    }

    public virtual DbSet<DataPullLogs> DataPullLogs { get; set; }

    public virtual DbSet<FiServeTotalEmpMeetingsView> FiServeTotalEmpMeetingsView { get; set; }

    public virtual DbSet<MeetingParticipantDateView> MeetingParticipantDateView { get; set; }

    public virtual DbSet<MeetingParticipantDateWithPhoneView> MeetingParticipantDateWithPhoneView { get; set; }

    public virtual DbSet<MeetingParticipantTimeView> MeetingParticipantTimeView { get; set; }

    public virtual DbSet<MeetingParticipants> MeetingParticipants { get; set; }

    public virtual DbSet<Meetings> Meetings { get; set; }

    public virtual DbSet<Tokens> Tokens { get; set; }

    public virtual DbSet<TotalTimePerMonthView> TotalTimePerMonthView { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<DataPullLogs>(entity =>
        {
            entity.Property(e => e.Parameters)
                .IsRequired()
                .HasMaxLength(1000);
            entity.Property(e => e.PullType)
                .IsRequired()
                .HasMaxLength(50);
        });

        modelBuilder.Entity<FiServeTotalEmpMeetingsView>(entity =>
        {
            entity
                .HasNoKey()
                .ToView("FiServeTotalEmpMeetingsView");

            entity.Property(e => e.DisplayName).HasMaxLength(700);
            entity.Property(e => e.Totaltime).HasColumnName("totaltime");
        });

        modelBuilder.Entity<MeetingParticipantDateView>(entity =>
        {
            entity
                .HasNoKey()
                .ToView("MeetingParticipantDateView");

            entity.Property(e => e.DisplayName).HasMaxLength(700);
            entity.Property(e => e.Email).HasMaxLength(500);
            entity.Property(e => e.EmployeeTime).HasColumnName("employeeTime");
            entity.Property(e => e.MeetingEnd).HasColumnType("datetime");
            entity.Property(e => e.MeetingId).HasMaxLength(500);
            entity.Property(e => e.MeetingStart).HasColumnType("datetime");
            entity.Property(e => e.Title).HasMaxLength(700);
        });

        modelBuilder.Entity<MeetingParticipantDateWithPhoneView>(entity =>
        {
            entity
                .HasNoKey()
                .ToView("MeetingParticipantDateWithPhoneView");

            entity.Property(e => e.DisplayName).HasMaxLength(700);
            entity.Property(e => e.Email).HasMaxLength(500);
            entity.Property(e => e.EmployeeTime).HasColumnName("employeeTime");
            entity.Property(e => e.MeetingEnd).HasColumnType("datetime");
            entity.Property(e => e.MeetingId).HasMaxLength(500);
            entity.Property(e => e.MeetingStart).HasColumnType("datetime");
            entity.Property(e => e.Title).HasMaxLength(700);
        });

        modelBuilder.Entity<MeetingParticipantTimeView>(entity =>
        {
            entity
                .HasNoKey()
                .ToView("MeetingParticipantTimeView");

            entity.Property(e => e.DisplayName).HasMaxLength(700);
            entity.Property(e => e.Email).HasMaxLength(500);
            entity.Property(e => e.Meetinglength).HasColumnName("meetinglength");
            entity.Property(e => e.Participantlength).HasColumnName("participantlength");
            entity.Property(e => e.Title).HasMaxLength(700);
        });

        modelBuilder.Entity<MeetingParticipants>(entity =>
        {
            entity.HasKey(e => e.DbId);

            entity.Property(e => e.DisplayName).HasMaxLength(700);
            entity.Property(e => e.Email).HasMaxLength(500);
            entity.Property(e => e.HostEmail).HasMaxLength(500);
            entity.Property(e => e.Id).HasMaxLength(500);
            entity.Property(e => e.JoinedTime).HasColumnType("datetime");
            entity.Property(e => e.LeftTime).HasColumnType("datetime");
            entity.Property(e => e.MeetingId).HasMaxLength(500);
            entity.Property(e => e.MeetingStartTime).HasColumnType("datetime");
            entity.Property(e => e.SiteUrl).HasMaxLength(1000);
            entity.Property(e => e.State).HasMaxLength(500);
        });

        modelBuilder.Entity<Meetings>(entity =>
        {
            entity.HasKey(e => e.DbId);

            entity.HasIndex(e => e.DbId, "DbId_MeetingsIndex");

            entity.Property(e => e.End).HasColumnType("datetime");
            entity.Property(e => e.HasQa).HasColumnName("HasQA");
            entity.Property(e => e.HostDisplayName).HasMaxLength(700);
            entity.Property(e => e.HostEmail).HasMaxLength(500);
            entity.Property(e => e.HostUserId).HasMaxLength(500);
            entity.Property(e => e.Id).HasMaxLength(500);
            entity.Property(e => e.MeetingNumber).HasMaxLength(500);
            entity.Property(e => e.MeetingSeriesId).HasMaxLength(500);
            entity.Property(e => e.MeetingType).HasMaxLength(500);
            entity.Property(e => e.ScheduledMeetingId).HasMaxLength(500);
            entity.Property(e => e.ScheduledType).HasMaxLength(500);
            entity.Property(e => e.SiteUrl).HasMaxLength(1000);
            entity.Property(e => e.Start).HasColumnType("datetime");
            entity.Property(e => e.State).HasMaxLength(500);
            entity.Property(e => e.Timezone).HasMaxLength(500);
            entity.Property(e => e.Title).HasMaxLength(700);
        });

        modelBuilder.Entity<Tokens>(entity =>
        {
            entity.Property(e => e.Token)
                .IsRequired()
                .HasMaxLength(1000);
            entity.Property(e => e.TokenName)
                .IsRequired()
                .HasMaxLength(50);
        });

        modelBuilder.Entity<TotalTimePerMonthView>(entity =>
        {
            entity
                .HasNoKey()
                .ToView("TotalTimePerMonthView");

            entity.Property(e => e.Endmonth)
                .HasColumnType("datetime")
                .HasColumnName("endmonth");
            entity.Property(e => e.Id).HasMaxLength(500);
            entity.Property(e => e.Participantlength).HasColumnName("participantlength");
            entity.Property(e => e.Startmonth)
                .HasColumnType("datetime")
                .HasColumnName("startmonth");
            entity.Property(e => e.Title).HasMaxLength(700);
        });

        OnModelCreatingGeneratedProcedures(modelBuilder);
        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}